apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: abdullah
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bma
  template:
    metadata:
      labels:
        app: bma
    spec:
      containers:
      - name: react-app
        image: abdullah78623/book-my-show3:v1'
        ports:
        - containerPort: 3000
